output   = "app/models"
wipe     = true
no-tests = true

[mysql]
  dbname = "aah-form-based-auth"
  host   = "localhost"
  port   = 3306
  user   = "root"
  pass   = "mysql"
  sslmode = "false"
  #blacklist = ["schema_migrations"]
