// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Permissions      string
	Roles            string
	Users            string
	UsersPermissions string
	UsersRoles       string
}{
	Permissions:      "permissions",
	Roles:            "roles",
	Users:            "users",
	UsersPermissions: "users_permissions",
	UsersRoles:       "users_roles",
}
